# Makefile for mpicxx compiler

SHELL = /bin/sh
#.IGNORE:

# System-specific settings

CC =		g++
CCFLAGS =	-O3 -DMDPREC=1 -DPREC_TIMER
LINK =		g++
LINKFLAGS = -O3
USRLIB =	
SYSLIB =	-lmcl -lOpenCL -lm -lpthread -lrt #-L/home/kama097/local/cuda-10.0/lib64/ -lcudart
SIZE =		size

# Link rule

$(EXE):	$(OBJ)
	$(LINK) $(LINKFLAGS) $(OBJ) $(USRLIB) $(SYSLIB) -o $(EXE)
	$(SIZE) $(EXE)
	

# Compilation rules

.cpp.o:
	$(CC) $(CCFLAGS) -c $<

# Individual dependencies

$(OBJ): $(INC)
