device = "nvdla"

[model]
[model.mnist]
path = "mnist/mnist.nvdla"

[model.mnist.kernels]
mnist = { input = "char*", output = "char*" }
mnist2 = { input1 = "char*", input2 = "char*", output = "char*" }

[model.mnist2]
path = "mnist/mnist.nvdla"

[model.mnist2.kernels]
mnist = { input = "char*", output = "char*" }